USE Railway;

DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS SCHEDULE;
DROP TABLE IF EXISTS TRAINSCHEDULEDATES;
DROP TABLE IF EXISTS TRAINTARIFF;
DROP TABLE IF EXISTS TRAIN;
DROP TABLE IF EXISTS TRAINROUTE;
DROP TABLE IF EXISTS PASSENGER;
DROP TABLE IF EXISTS STATION;


CREATE TABLE IF NOT EXISTS USER (
  USER_ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(255) NOT NULL ,
  PASSWORD  VARCHAR(255) NOT NULL,
  EMAIL  VARCHAR(255) NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  PRIMARY KEY(USERNAME),
  KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS AUTHORITIES(
  USERNAME VARCHAR(255) NOT NULL,
  AUTHORITY VARCHAR(255) NOT NULL,
  CONSTRAINT FK_AUTHORITIES_USER FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS STATION (
  STATION_ID INT AUTO_INCREMENT NOT NULL,
  STATIONNAME NVARCHAR(255) NOT NULL,
  PRIMARY KEY (`STATION_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS TRAINROUTE (
  TRAINROUTE_ID INT AUTO_INCREMENT NOT NULL,
  TRAIN_ID INT NOT NULL,
  FROMSTATION INT NOT NULL,
  TOSTATION INT NOT NULL,
  PRIMARY KEY (`TRAINROUTE_ID`),
  KEY `FROMSTATION` (`FROMSTATION`),
  KEY `TOSTATION` (`TOSTATION`),
  KEY `TRAIN_ID` (`TRAIN_ID`),
  CONSTRAINT `items_ibfk_tr_2` FOREIGN KEY (`FROMSTATION`) REFERENCES `STATION` (`STATION_ID`),
  CONSTRAINT `items_ibfk_tr_3` FOREIGN KEY (`TOSTATION`) REFERENCES `STATION` (`STATION_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS TRAIN (
  TRAIN_ID INT AUTO_INCREMENT NOT NULL,
  TRAINNAME NVARCHAR(255),
  TRAINCODE NVARCHAR(255) NOT NULL,
  SEATSNUMBER INT NOT NULL,
  PRIMARY KEY (`TRAIN_ID`),
  CONSTRAINT `items_tr_21_s` FOREIGN KEY (`TRAIN_ID`) REFERENCES `TRAINROUTE` (`TRAIN_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS SCHEDULE (
  SCHEDULE_ID INT AUTO_INCREMENT NOT NULL,
  SCHEDULENAME NVARCHAR(255),
  TRAIN_ID INT NOT NULL,
  ARRIVAL_STATION_ID INT NOT NULL,
  DEPARTURE_STATION_ID INT NOT NULL,
  INTERVAL_M INT NOT NULL,
  PRIMARY KEY (`SCHEDULE_ID`),
  KEY `ARRIVAL_STATION_ID` (`ARRIVAL_STATION_ID`),
  KEY `DEPARTURE_STATION_ID` (`DEPARTURE_STATION_ID`),
  KEY `TRAIN_ID` (`TRAIN_ID`),
  CONSTRAINT `items_ibfk_1` FOREIGN KEY (`ARRIVAL_STATION_ID`) REFERENCES `STATION` (`STATION_ID`),
  CONSTRAINT `items_ibfk_1a` FOREIGN KEY (`DEPARTURE_STATION_ID`) REFERENCES `STATION` (`STATION_ID`),
  CONSTRAINT `items_ibfk_2` FOREIGN KEY (`TRAIN_ID`) REFERENCES `TRAIN` (`TRAIN_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS TRAINSCHEDULEDATES (
  TRAINSCHEDULE_ID INT AUTO_INCREMENT NOT NULL,
  TRAIN_ID INT NOT NULL,
  DEPARTUREDATE DATETIME NOT NULL,
  PRIMARY KEY (`TRAINSCHEDULE_ID`),
  KEY `TRAIN_ID` (`TRAIN_ID`),
  CONSTRAINT `items_ibfk_tsd_1` FOREIGN KEY (`TRAIN_ID`) REFERENCES `TRAIN` (`TRAIN_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS TRAINTARIFF (
  TARIFF_ID INT AUTO_INCREMENT NOT NULL,
  TRAIN_ID INT NOT NULL,
  ARRIVAL_STATION_ID INT NOT NULL,
  DEPARTURE_STATION_ID INT NOT NULL,
  TARIFF DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`TARIFF_ID`),
  KEY `ARRIVAL_STATION_ID` (`ARRIVAL_STATION_ID`),
  KEY `DEPARTURE_STATION_ID` (`DEPARTURE_STATION_ID`),
  KEY `TRAIN_ID` (`TRAIN_ID`),
  CONSTRAINT `items_tt_1` FOREIGN KEY (`ARRIVAL_STATION_ID`) REFERENCES `STATION` (`STATION_ID`),
  CONSTRAINT `items_tt_1a` FOREIGN KEY (`DEPARTURE_STATION_ID`) REFERENCES `STATION` (`STATION_ID`),
  CONSTRAINT `items_tt_2` FOREIGN KEY (`TRAIN_ID`) REFERENCES `TRAIN` (`TRAIN_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS PASSENGER (
  PASSENGER_ID INT AUTO_INCREMENT NOT NULL,
  FIRSTNAME NVARCHAR(255) NOT NULL,
  FAMILYNAME NVARCHAR(255) NOT NULL,
  BIRTHDATE DATE NOT NULL,
  PRIMARY KEY (`PASSENGER_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS TICKET (
  IDTICKET INT AUTO_INCREMENT NOT NULL,
  PASSENGER_ID INT NOT NULL,
  TRAINCODE NVARCHAR(255) NOT NULL,
  DEPARTUREDATE DATE NOT NULL,
  PRIMARY KEY (`IDTICKET`),
  KEY `PASSENGER_ID` (`PASSENGER_ID`),
  CONSTRAINT `items_ibfk_3` FOREIGN KEY (`PASSENGER_ID`) REFERENCES `PASSENGER` (`PASSENGER_ID`)
  ) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;